name: Paper Test CI

on:
  push:
    branches-ignore: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Get JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary: never
          generate-job-summary: false
          cache-read-only: false

      - name: Apply Patches
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          ./gradlew applyPatches --stacktrace

      - name: Build
        run: ./gradlew build --stacktrace

      - name: Create Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Upload Paperclip Jar
        uses: actions/upload-artifact@v4
        with:
          name: paper-${{ fromJSON(steps.determine.outputs.result).pr }}
          path: paper-server/build/libs/paper-paperclip-*-mojmap.jar
